# see https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md

AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Edhi takes care of users

Parameters:
  DeploymentPreferenceType:
    Type: String
    Description: SAM traffic shifting configuration
    AllowedValues:
      - Canary10Percent30Minutes
      - Canary10Percent5Minutes
      - Canary10Percent10Minutes
      - Canary10Percent15Minutes
      - AllAtOnce
      - Linear10PercentEvery10Minutes
      - Linear10PercentEvery1Minute
      - Linear10PercentEvery2Minutes
      - Linear10PercentEvery3Minutes
  LightrailDomain:
    Type: String
    Description: The domain of the Lightrail REST API
    AllowedPattern: (\w+\.)+\w{3}
  LightrailEmailDomain:
    Type: String
    Description: The lightrail email domain.
    AllowedPattern: (\w+\.)+\w+
  LightrailWebappDomain:
    Type: String
    Description: The domain of the Lightrail web app
    AllowedPattern: (\w+\.)+\w+
  SecureConfigBucket:
    Type: String
    Description: Name of the S3 bucket holding the JWT secure config
  SecureConfigKmsArn:
    Type: String
    Description: Optional ARN of the KMS encrypting SecureConfigBucket
    AllowedPattern: arn:aws:kms:[a-zA-Z_0-9\-]+:\d{12}:key/[a-zA-Z_0-9+=,.@\-_/]+
  SentryDsn:
    Type: String
    Description: You can find your project’s DSN in the “Client Keys” section of your “Project Settings” in Sentry.
    AllowedPattern: (https://[0-9a-f]+@o[0-9a-f]+.ingest.sentry.io/[0-9]+)?
  WebAclArn:
    Type: String
    Description: ARN of the WebACL protecting the REST API
    AllowedPattern: arn:aws:wafv2:us-east-1:\d+:global/webacl/.*/.*

Resources:
  ObjectTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: pk2
          AttributeType: S
        - AttributeName: sk2
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: EdhiIx2
          KeySchema:
            - AttributeName: pk2
              KeyType: HASH
            - AttributeName: sk2
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        - Key: ShortName
          Value: ObjectTable
        - Key: Service
          Value: Edhi

  # ObjectTable autoscaling
  ObjectTableWriteCapacityScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 100
      MinCapacity: 5
      ResourceId: !Sub "table/${ObjectTable}"
      RoleARN: !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-service-role/dynamodb.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_DynamoDBTable"
      ScalableDimension: dynamodb:table:WriteCapacityUnits
      ServiceNamespace: dynamodb
  ObjectTableWriteScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: WriteAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ObjectTableWriteCapacityScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBWriteCapacityUtilization
  ObjectTableReadCapacityScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 100
      MinCapacity: 5
      ResourceId: !Sub "table/${ObjectTable}"
      RoleARN: !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-service-role/dynamodb.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_DynamoDBTable"
      ScalableDimension: dynamodb:table:ReadCapacityUnits
      ServiceNamespace: dynamodb
  ObjectTableReadScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: ReadAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ObjectTableReadCapacityScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBReadCapacityUtilization

  # ObjectTable global secondary index autoscaling
  ObjectTableIx2WriteCapacityScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 100
      MinCapacity: 5
      ResourceId: !Sub "table/${ObjectTable}/index/EdhiIx2"
      RoleARN: !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-service-role/dynamodb.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_DynamoDBTable"
      ScalableDimension: dynamodb:index:WriteCapacityUnits
      ServiceNamespace: dynamodb
  ObjectTableIx2WriteScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: WriteAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ObjectTableIx2WriteCapacityScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBWriteCapacityUtilization
  ObjectTableIx2ReadCapacityScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 100
      MinCapacity: 5
      ResourceId: !Sub "table/${ObjectTable}/index/EdhiIx2"
      RoleARN: !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-service-role/dynamodb.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_DynamoDBTable"
      ScalableDimension: dynamodb:index:ReadCapacityUnits
      ServiceNamespace: dynamodb
  ObjectTableIx2ReadScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: ReadAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ObjectTableIx2ReadCapacityScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBReadCapacityUtilization

  EdhiSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Encrypts Edhi secrets.  32 bytes as hex encoded string.
      GenerateSecretString:
        PasswordLength: 64
        ExcludeCharacters: 'GHIJKLMNOPQRSTUVWXYZghijklmnopqrstuvwxyz'
        ExcludeLowercase: false
        ExcludeUppercase: true
        ExcludePunctuation: true
        IncludeSpace: false
      Tags:
        - Key: Service
          Value: Edhi

  RestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist/rest/rest.zip
      Handler: index.handler
      Runtime: nodejs10.x
      MemorySize: 256
      Timeout: 30 # seconds, 300 max
      AutoPublishAlias: live # see https://github.com/awslabs/serverless-application-model/blob/master/docs/safe_lambda_deployments.rst
      DeploymentPreference:
        Type: !Ref DeploymentPreferenceType
        Alarms:
          - !Ref RestFunctionAliasErrorMetricGreaterThanZeroAlarm
          - !Ref RestFunctionLatestVersionErrorMetricGreaterThanZeroAlarm
          - !Ref EdhiApiGateway5XXGreaterThanZeroAlarm
      Environment:
        Variables:
          API_KEY_BLOCKLISTER_QUEUE_URL: !Ref ApiKeyBlocklisterQueue
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
          ENCRYPTION_SECRET_ID: !Ref EdhiSecret
          LIGHTRAIL_DOMAIN: !Ref LightrailDomain
          LIGHTRAIL_EMAIL_DOMAIN: !Ref LightrailEmailDomain
          LIGHTRAIL_WEBAPP_DOMAIN: !Ref LightrailWebappDomain
          OBJECT_TABLE: !Ref ObjectTable
          SECURE_CONFIG_BUCKET: !Ref SecureConfigBucket
          SECURE_CONFIG_KEY_ASSUME_STORAGE_SCOPE_TOKEN: assumeStorageScopeToken.json
          SECURE_CONFIG_KEY_INTERCOM_SECRET: intercom_secrets.json
          SECURE_CONFIG_KEY_JWT: authentication_badge_key.json
          SECURE_CONFIG_KEY_ROLE_DEFINITIONS: RoleDefinitions.json
          SECURE_CONFIG_KEY_STRIPE: stripe_connect.json
          SECURE_CONFIG_KEY_TWILIO: twilio.json
          SENTRY_DSN: !Ref SentryDsn
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource:
                - !Sub "arn:aws:s3:::${SecureConfigBucket}/assumeStorageScopeToken.json"
                - !Sub "arn:aws:s3:::${SecureConfigBucket}/authentication_badge_key.json"
                - !Sub "arn:aws:s3:::${SecureConfigBucket}/intercom_secrets.json"
                - !Sub "arn:aws:s3:::${SecureConfigBucket}/RoleDefinitions.json"
                - !Sub "arn:aws:s3:::${SecureConfigBucket}/stripe_connect.json"
                - !Sub "arn:aws:s3:::${SecureConfigBucket}/twilio.json"
            - Effect: Allow
              Action:
                - kms:Decrypt
                - kms:DescribeKey
              Resource:
                - !Ref SecureConfigKmsArn
              Condition:
                StringLike:
                  "kms:ViaService":
                    !Sub "s3.${AWS::Region}.amazonaws.com"
                  "kms:EncryptionContext:aws:s3:arn":
                    !Sub "arn:aws:s3:::${SecureConfigBucket}/*"
            - Effect: Allow
              Action:
                - dynamodb:BatchGetItem
                - dynamodb:DescribeTable
                - dynamodb:DeleteItem
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:Query
                - dynamodb:UpdateItem
              Resource:
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ObjectTable}"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ObjectTable}/*"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ObjectTable}/*/index/EdhiIx2"
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: !Sub "arn:aws:ses:${AWS::Region}:${AWS::AccountId}:identity/${LightrailEmailDomain}"
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Ref EdhiSecret
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource:
                - !GetAtt ApiKeyBlocklisterQueue.Arn
      Tags:
        ShortName: RestFunction
        Service: Edhi
      Events:
        RestApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        KeepWarmSchedule:
          Type: Schedule
          Properties:
            Schedule: rate(4 minutes)
            Input: !Sub "{\"resource\":\"/{proxy+}\",\"path\":\"/v2/user/healthCheck\",\"httpMethod\":\"GET\",\"headers\":null,\"queryStringParameters\":null,\"pathParameters\":null,\"stageVariables\":null,\"context\":{\"accountId\":\"12345678912\",\"resourceId\":null,\"stage\":\"Prod\",\"requestId\":null,\"identity\":null,\"resourcePath\":\"/{proxy+}\",\"httpMethod\":\"GET\",\"apiId\":null},\"body\":null,\"isBase64Encoded\":false}"

  RestFunctionAliasErrorMetricGreaterThanZeroAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Lambda Function Error > 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Resource
          Value: !Sub "${RestFunction}:live"
        - Name: FunctionName
          Value: !Ref RestFunction
      EvaluationPeriods: 2
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0

  RestFunctionLatestVersionErrorMetricGreaterThanZeroAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Lambda Function Error > 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Resource
          Value: !Sub "${RestFunction}:live"
        - Name: FunctionName
          Value: !Ref RestFunction
        - Name: ExecutedVersion
          Value: !GetAtt RestFunction.Version.Version
      EvaluationPeriods: 2
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0

  EdhiApiGateway5XXGreaterThanZeroAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: ApiGateway 5XX > 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Ref AWS::StackName
        - Name: Stage
          Value: Prod
      EvaluationPeriods: 2
      MetricName: 5XXError
      Namespace: AWS/ApiGateway
      Period: 60
      Statistic: Sum
      Threshold: 0

  ApiKeyBlocklisterQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 604800 # in seconds (7 days)
      VisibilityTimeout: 900 # in seconds (15 minutes)

  ApiKeyBlocklisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist/apiKeyBlocklister/apiKeyBlocklister.zip
      Handler: index.handler
      Runtime: nodejs10.x
      MemorySize: 256
      Timeout: 300 # seconds, 300 max
      ReservedConcurrentExecutions: 1
      AutoPublishAlias: live # see https://github.com/awslabs/serverless-application-model/blob/master/docs/safe_lambda_deployments.rst
      Environment:
        Variables:
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
          OBJECT_TABLE: !Ref ObjectTable
          SECURE_CONFIG_BUCKET: !Ref SecureConfigBucket
          SECURE_CONFIG_KEY_JWT: authentication_badge_key.json
          SENTRY_DSN: !Ref SentryDsn
          WEB_ACL_ARN: !Ref WebAclArn
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource:
                - !Sub "arn:aws:s3:::${SecureConfigBucket}/authentication_badge_key.json"
            - Effect: Allow
              Action:
                - kms:Decrypt
                - kms:DescribeKey
              Resource:
                - !Ref SecureConfigKmsArn
              Condition:
                StringLike:
                  "kms:ViaService":
                    !Sub "s3.${AWS::Region}.amazonaws.com"
                  "kms:EncryptionContext:aws:s3:arn":
                    !Sub "arn:aws:s3:::${SecureConfigBucket}/*"
            - Effect: Allow
              Action:
                - dynamodb:BatchGetItem
                - dynamodb:DescribeTable
                - dynamodb:GetItem
                - dynamodb:Query
              Resource:
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ObjectTable}"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ObjectTable}/*"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ObjectTable}/*/index/EdhiIx2"
            - Effect: Allow
              Action:
                - wafv2:GetWebACL
                - wafv2:UpdateWebACL
              Resource:
                - !Ref WebAclArn
            - Effect: Allow
              Action:
                - sqs:ChangeMessageVisibility
                - sqs:DeleteMessage
                - sqs:ReceiveMessage
                - sqs:SendMessage
              Resource:
                - !GetAtt ApiKeyBlocklisterQueue.Arn
      Tags:
        ShortName: ApiKeyBlocklister
        Service: Edhi
      Events:
        InvokeQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt ApiKeyBlocklisterQueue.Arn
            BatchSize: 10
            Enabled: true
