# see https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md

AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Edhi takes care of users

Parameters:
  Capacity:
    Type: String
    Description: Level of production capacity to use (high or low)
    AllowedPattern: (high|low)
    Default: low
  LightrailDomain:
    Type: String
    Description: The domain of the Lightrail REST API
    AllowedPattern: (\w+\.)+\w{3}
  LightrailEmailDomain:
    Type: String
    Description: The lightrail email domain.
    AllowedPattern: (\w+\.)+\w{3}
  LightrailWebappDomain:
    Type: String
    Description: The domain of the Lightrail web app
    AllowedPattern: (\w+\.)+\w{3}

Conditions:
  UseProductionCapacity: !Equals [!Ref Capacity, high]

Resources:
  EmailVerificationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: token
          AttributeType: S
      KeySchema:
        - AttributeName: token
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: ShortName
          Value: EmailVerificationTable
        - Key: Service
          Value: Edhi

  OrganizationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: !If [UseProductionCapacity, 70, 8]
        WriteCapacityUnits: !If [UseProductionCapacity, 35, 8]
      Tags:
        - Key: ShortName
          Value: OrganizationTable
        - Key: Service
          Value: Edhi

  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: !If [UseProductionCapacity, 70, 8]
        WriteCapacityUnits: !If [UseProductionCapacity, 35, 8]
      Tags:
        - Key: ShortName
          Value: UserTable
        - Key: Service
          Value: Edhi

  RestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist/rest/rest.zip
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 128
      Timeout: 30 # seconds, 300 max
      Environment:
        Variables:
          EMAIL_VERIFICATION_TABLE: !Ref EmailVerificationTable
          LIGHTRAIL_DOMAIN: !Ref LightrailDomain
          LIGHTRAIL_EMAIL_DOMAIN: !Ref LightrailEmailDomain
          LIGHTRAIL_WEBAPP_DOMAIN: !Ref LightrailWebappDomain
          ORGANIZATION_TABLE: !Ref OrganizationTable
          USER_TABLE: !Ref UserTable
